### ISSUE TITLE
Variables vocabularies

### ISSUE THREAD

**Issue by paolap** [ACDguide/invenioClim#1]
For the moment we are trialling a mixed of grouped variable (i.e. aerosols) and specific names for common variables (i.e. surface_air_temperature).
Specific variable names have to be present if we want later on add a comparison table in the style of the [reanalysis.org ones] (https://reanalyses.org/atmosphere/comparison-table/). But comparing datasets for a specific variable: for example all precipitation datasets organised by spatial and temporal resolution.

We need to work out a suitable list, so use this ticket for the discussion.

The relevant vocabulary is [variables.yaml](https://github.com/ACDguide/invenioClim/blob/main/app_data/vocabularies/variables.yaml).

To directly contribute new terms use this [spreadsheet](https://docs.google.com/spreadsheets/d/1SmIyHfG0OaSnCRmolhnud9eXgm4AJBL2L9dJ_GJ-hK0/edit#gid=0).
It's just a draft to demonstrate so feel free to make/propose changes. It's important to properly defined what each term is covering as best as possible so we can publish it and give clear information to both users and contributors on the terms' meaning.

**Comment by hot007** [comment]
Cross reference with variables available at the UCAR climate data guide? https://climatedataguide.ucar.edu/

**Comment by hot007** [comment]
I added waves to the spreadsheet but it doesn't seem to be in `variables.yaml`?

**Comment by paolap** [comment]
Nope was one of there things I was going to do this week, I will check the spreadsheet and updates this list next week :-)

**Comment by paolap** [comment]
Finally getting back to this while checking a definition I ended up in the advance search page of the near climate data guide. We don't have to do exactly the same but it's a good example of what we're trying to achieve with the vocabularies: https://climatedataguide.ucar.edu/climate-data/advanced_search

**Comment by paolap** [comment]
Added waves, but this vac definitely need more work and a clear strategy: https://github.com/ACDguide/invenioClim/commit/faf45ee18ca558e17f5daa467b94f990864a6cb0

**Comment by paolap** [comment]
I've temporarily (?) removed this to see how we go using only realms and potentially listing variables in the records to find via free-text search

**Comment by paolap** [comment]
We decided to just se realms, so this can be closed
