### ISSUE TITLE
Spatial resolution vocabulary

### ISSUE THREAD

**Issue by paolap** [ACDguide/invenioClim#2]
We haven't added yet a vocabulary to identify spatial resolution, as we don't have a strategy on how to define it.

Things to consider:

- spatial resolution will be defined both in "metres" and "degrees" units
- it's unrealistic to cover all possible values
- we can use ranges, specific values or a mixtures

Only example I found so far is from the [GCMD keywords](https://gcmd.earthdata.nasa.gov/static/kms/).

**Comment by paolap** [comment]
Useful document for comparison, also for temporal resolution

https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Annex_I.pdf

and we could also check CMIP6 approximate horizontal resolution

**Comment by hot007** [comment]
I feel like I have nothing useful to add given the ESGF interface has so many spatial resolution facets and that's within a project where it should be viable to constrain them! That being said, where we **do** have a spatial resolution of any form given we should include it - problem is the user might then expect to be able to search on resolution when that may not be feasible as it might just not be trivial for many datasets.
Furthermore, while global datasets are often cartesian gridded so "spatial resolution" is a sensible thing to talk about, many regional models are increasingly moving to unstructured grids to get higher resolutions around coasts, tropical cyclones, eddies, etc., meaning there is a "maximum resolution" but elsewhere in the domain the data may be much coarser. 

Maybe we shouldn't even include resolution as a category/vocabulary??

**Comment by paolap** [comment]
"problem is the user might then expect to be able .." we could solve this by having good visible documentation on queries and specifying resolution information might not always be available.
Even if the results are approximate I reckon it would still help screening data if resolution is an important criteria for the user.
"many regional models are increasingly moving to unstructured grids ..." could this be taken care for by  
adopting the range model and calling the filed approximate resolution (as for CMIP6)??
While we're not sure to keep this I'll try to update the fields following that just to have an example for the next meeting.

**Comment by paolap** [comment]
Up to now we've been ignoring surface versus 3D spatial data, is that a more useful distinction then some for he other flags? I guess I should open a separate ticket for this

**Comment by paolap** [comment]
Added example vocabularies based on the GCMD keywords and checked against the IPCC climate data list : https://github.com/ACDguide/invenioClim/commit/faf45ee18ca558e17f5daa467b94f990864a6cb0

**Comment by paolap** [comment]
specify for ex. 1km is in 500m-1km
