### ISSUE TITLE
Cannot edit a record once submitted for review

### ISSUE THREAD

**Issue by heroldn** [ACDguide/invenioClim#25]
Probably not an issue but more a choice. I can't edit a record once it's submitted for review. If this is an option I think it should be allowed. As I've seen something I want to change and now have to wait and record that info elsewhere.

**Comment by heroldn** [comment]
Arg forget this, I think I can by just saying "Save Draft".

**Comment by paolap** [comment]
You should also be able to do it from the community page in fact anyone who is a "manager" of the community would be able to. As well records can still be edited after publication. What you can't change is the attached files/doi
