### ISSUE TITLE
Search potentially not working properly

### ISSUE THREAD

**Issue by heroldn** [ACDguide/invenioClim#26]
**Context:** There are two records with "HadEX" in the title. 
**Problem:** When I search "HadEX" though only one record ("HadEX2...") shows up.
**Expected behaviour:** When searching "HadEX", both the "HadEX2..." and "HadEX3..." records should show up. Oddly, if you search "HadEX3" then the "HadEX3" record does show, indicating it is in the database.

**Comment by paolap** [comment]
Not much I can do with that I think it's because it searches for the full word by default you can use the "?" wildcard: "HadEX?" will include both. It is covered in the search guide page:

https://oneclimate.acdguide.cloud.edu.au/help/search
