### ISSUE TITLE
Frequency vocabulary

### ISSUE THREAD

**Issue by hot007** [ACDguide/invenioClim#3]
Is it sufficient to list "sub-daily" as a field or should we have all the individual values?
If this is for search, is a user more likely to look for "sub daily" or "3 hour" or "10 min" etc? if we use "sub-daily" as a catch all then I think we need to ensure there is a mapping of search terms for "hour" and "min" to "sub-daily", might be easier to just list all the temporal resolutions and double-tag the datasets affected with e.g. "30 min" and "subdaily"?

Myself as a user I'm more likely to look for 'hourly' than 'sub-daily' because I don't want 6-hourly...

**Comment by heroldn** [comment]
Agree with all in the above. 

Also, there should probably be a "Seasonal" id, currently there's "Seasonal climatology" but not "Seasonal".

**Comment by paolap** [comment]
I'm not 100% sure I got this right but I added 
1) seasonal
2) 1-hourly
3) 3-hourly
4) 6-hourly
5) 12-hourly
6) 30-min
7) Event
8) weekly

I'm not sure about the 30-min is that sufficient or there could be even higher frequencies?
I temporarily removed sub-daily but we can add it again later if someone think is useful.
If we list all possible values might be a bit more of a pain to have to tag every dataset twice
Event is used in this doc: https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Annex_I.pdf

Again as for other vocabularies changes it will appear in next commit (https://github.com/ACDguide/invenioClim/commit/faf45ee18ca558e17f5daa467b94f990864a6cb0)

**Comment by heroldn** [comment]
I like the addition of "event". I think it is possible someone has sub 30 minute data (maybe Blair can comment, I'm thinking of weather stations) so perhaps one bookend/umbrella category that's "sub 30-min"?

**Comment by paolap** [comment]
Thanks for spotting that, I meant to add it and forgot, it's there now. By the way I messed up the commit last time and doubled up the vocabularies folder, I fixed that now!

**Comment by paolap** [comment]
Add irregular, remove weekly and put instead 1 day to 1 month
pentad/ multiyear
