### ISSUE TITLE
Search box improvements

### ISSUE THREAD

**Issue by hot007** [ACDguide/invenioClim#4]
- Change the greyed out text "Search" to "search datasets. e.g. temperature".

- Add "advanced search" link which takes you to the filter ESGF-like view.

- Consider adding small text below search box giving a couple of examples of what it's for.

We could remove it entirely but get user feedback first.

**Comment by paolap** [comment]
I've started implementing some changes to the front-page:

https://test.dmponline.cloud.edu.au
