### ISSUE TITLE
Resource type vocabulary

### ISSUE THREAD

**Issue by heroldn** [ACDguide/invenioClim#6]
There's currently "dataset-sat" and "dataset-obs". Should "dataset-obs" be renamed "dataset-station"? As many end users might consider remote sensing data to be observations (even if there's a legitimate argument that they are not obs).

**Comment by hot007** [comment]
That's a good point. I'm used to the 'sat' and 'obs' nomenclature but that doesn't mean it's right, seeing as you say, it's fair to consider remote sensing data to be 'obs', and there's some cross over between satellite based platforms and aerial platforms. What words are typically used in the remote sensing community? It does make sense to use 'station' to mean 'non-moving obs platform'.

**Comment by paolap** [comment]
I changed that should appear in next commit (https://github.com/ACDguide/invenioClim/commit/faf45ee18ca558e17f5daa467b94f990864a6cb0)

**Comment by heroldn** [comment]
On reflection, maybe I'm being too narrow minded and thinking of my own experience. I can see how "obs" can be separate to "sat", and that "obs" may incorporate more than just stations (if we're talking about marine drones or who knows what that's collecting in situ data). I now lean towards the current obs / sat distinction, noting that yes some products are a blend.

Sorry for being fickle! Maybe something to discuss next meeting.

**Comment by paolap** [comment]
No problem being fickle at all, it's great to have a discussion going on. For the moment I'll leave it as it is and we can discuss it on Friday, feel free to add more comments. The [advanced search on the ncar climate data guide](https://climatedataguide.ucar.edu/climate-data/advanced_search) might be a helpful example to finalise these vocabularies. I'll look for other examples before Friday

**Comment by paolap** [comment]
I'm adding:
- Other observations subtype, as we currently have Satellite and In Situ but there are many other observations that wouldn't quite fit and as we won't have a lot of records for these we might as well have a "catch all" category.

- Changing Collection-In situ to Collection observations as more generic. There's still collection satellite, we could remove it in favour to eh generic option, but collection of satellite data might be relatively common. 

- reanalysis as it's a mix between model and observations

- metadata record, this is only to be able to better define links

**Comment by paolap** [comment]
Other additions after checking the latest DataCite schema (v4.4):

- Computational model (as subtype of software): to list models used by the community not just their output (?), but also should be useful when linking to model code
- Computational notebook (subtype of software)
- Event : eventually we could list relevant conferences, regularly occurring training/seminars? or recorded seminars 
- Standard - again eventually a way to list conventions/standards used
